FROM openjdk:17-oracle

EXPOSE 8080

ADD target/banking-sprint-project-0.0.1-SNAPSHOT.jar banking-sprint-project-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","banking-sprint-project-0.0.1-SNAPSHOT.jar"]